---
title: Fawcett East London
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: fawcetteastldn@gmail.com
description: Fawcett East London
baseurl: 
permalink: "/blog/:year/:title:output_ext"
exclude:
- fetchevents.js
